;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-semi&comma
        c-indent-line-or-region
        comment-dwim
        electric-newline-and-maybe-indent
        forward-sexp
        hungry-delete-backward
        hungry-delete-forward
        kill-region
        markdown-outdent-or-delete
        mouse-buffer-menu
        skk-previous-candidate
        skk-undo
        ))

(setq mc/cmds-to-run-once
      '(
        skk-insert
        ))
